id: 0dfaab184aca44e2acfa6f4050511faa
title: Toh_122-Wisdom_at_the_Hour_of_Death-v1
type: translation
source_metadata:
  creationtool: 84000-translation-memory
  creationtoolversion: 1.0.0.0
  datatype: PlainText
  segtype: phrase
  adminlang: en
  srclang: bo
  o-tmf: TEI
  creationdate: '2018-03-26T16:01:47.493Z'
  creationid: celso
  eft-text-id: UT22084-054-003
  eft-text-version: 1.2 2016
  xmlns-eft: http://read.84000.co/ns/1.0
